all: ptr2str str2ptr get_stack_ptr hex_shell2str

ptr2str:
	g++ pointer_to_string.cpp -o ptr2str

str2ptr:
	g++ string_to_pointer.cpp -o str2ptr

get_stack_ptr:
	g++ get_stack_pointer.c -o get_stack_ptr

hex_shell2str:
	g++ hex_shell_code_to_string.cpp -o hex_shell2str
